### ISSUE TITLE
Binary Ninja Dev channel compatibility

### ISSUE THREAD

**Issue by v-p-b** [pbiernat/ripr#19]
I'm getting the following error in 1.1.1461-dev:

```
Traceback (most recent call last):
  File "/path/to/.binaryninja/plugins/ripr/__init__.py", line 18, in <module>
    ui = gui.riprWidget()
  File "/path/to/.binaryninja/plugins/ripr/gui.py", line 92, in __init__
    super(riprWidget, self).__init__('ripr')
  File "/path/to/.binaryninja/plugins/ripr/defunct/widgets.py", line 80, in __init__
    self._core = instance()
  File "/path/to/.binaryninja/plugins/ripr/defunct/__init__.py", line 37, in instance
    dock = BinjaDockWidget()
  File "/path/to/.binaryninja/plugins/ripr/defunct/widgets.py", line 38, in __init__
    self._tool_menu = [x for x in self._main_window.menuWidget().children() if x.__class__ is QtWidgets.QMenu and x.title() == u'&Tools'][0]
AttributeError: 'NoneType' object has no attribute 'children'
```

Stable loads fine. I guess this is a result of an API change, but didn't have the time to investigate further...

**Comment by psifertex** [comment]
Another that can be closed.
