### ISSUE TITLE
Can seem to find a solution to this i am on debian 

### ISSUE THREAD

**Issue by zglozman** [pbiernat/ripr#7]
Traceback (most recent call last):
  File "/home/zglozman/.binaryninja/plugins/ripr/__init__.py", line 7, in <module>
    from analysis_engine import *
  File "/home/zglozman/.binaryninja/plugins/ripr/analysis_engine.py", line 13, in <module>
    import gui
  File "/home/zglozman/.binaryninja/plugins/ripr/gui.py", line 8, in <module>
    from PyQt5 import QtWidgets, QtGui, QtCore
ImportError: /home/zglozman/binaryninja/libQt5Core.so.5: version `Qt_5.7' not found (required by /usr/lib/python2.7/dist-packages/PyQt5/QtWidgets.x86_64-linux-gnu.so)
Python plugin 'ripr' could not be loaded

**Comment by sheriffsparks** [comment]
Is python-pyqt5 installed?

**Comment by zglozman** [comment]
Yes off course
